# Generated by Django 3.0.6 on 2020-05-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='product',
            field=models.ManyToManyField(to='product.Products'),
        ),
        migrations.DeleteModel(
            name='BillsProducts',
        ),
    ]
